- hosts: all
  become: yes
  become_user: root

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - ./vars.yml

  tasks:
    - name: install necessary packages
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - postgresql-client
        - postgresql-contrib

    # - name: create replica user
    #   postgresql_user:
    #     name: replica
    #     password: "{{ replica_user_password }}"
    #     role_attr_flags: SUPERUSER

    - name: add replica user
      shell: sudo -u postgres psql CREATE USER replica REPLICATION LOGIN ENCRYPTED PASSWORD 'lmsreplica';
